import os
from dotenv import load_dotenv

load_dotenv()

AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY=os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_DEFAULT_REGION=os.getenv("AWS_DEFAULT_REGION")
MLFLOW_S3_ENDPOINT_URL=os.getenv("MLFLOW_S3_ENDPOINT_URL")
TRACKING_URI=os.getenv("MLFLOW_TRACKING_URI")
EXPERIMENT_NAME=os.getenv("MLFLOW_EXPERIMENT_NAME")
